# Sample config file

# Dracula theme
theme:
  active: "80,250,123"                 # current playing song in list
  banner: "80,250,123"                 # the "spotify-tui" banner on launch
  error_border: "255,85,85"            # error dialog border
  error_text: "248,248,242"            # error message text (e.g. "Spotify API
                                       # reported error 404")
  hint: "241,250,140"                  # hint text in errors
  hovered: "80,250,123"                # hovered pane border
  inactive: "248,248,242"              # borders of inactive panes
  playbar_background: "68,71,90"       # background of progress bar
  playbar_progress: "248,248,242"      # filled-in part of the progress bar
  playbar_progress_text: "248,248,242" # song length and time played/left
                                       # indicator in the progress bar
  playbar_text: "248,248,242"          # artist name in player pane
  selected: "202,169,250"              # a) selected pane border, b) hovered item
                                       # in list, & c) track title in player
  text: "248,248,242"                  # text in panes
  header: "248,248,242"                # header text in panes (e.g. 'Title',
                                       # 'Artist', etc.)

# Behavior and icons
behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  tick_rate_milliseconds: 250
  enable_text_emphasis: true
  show_loading_indicator: true
  liked_icon: ♥
  shuffle_icon: 🔀
  repeat_track_icon: 🔂
  repeat_context_icon: 🔁
  playing_icon: ▶
  paused_icon: ⏸

# Keybindings
keybindings:
  back: "ctrl-q"
  jump_to_album: "a"
  jump_to_artist_album: "A"
  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  shuffle: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "q"
